apiVersion: v1
kind: Pod
metadata:
  name: add-pod
  labels:
    app.kubernetes.io/name: hello
spec:
  containers:
   - name: add-pod-container
     image: busybox
     command: ["sh", "-c", "echo Hello from my container! && sleep 3600"]
